### ISSUE TITLE
Cross site scripting bug

### ISSUE THREAD

**Issue by TiagoJacobs** [lon-yang/ngx-markdown-editor#110]
Hello, would it be possible to disable HTML in this editor?

If you input an HTML `<img` with this code, the code is executed, making it unsafe:

```
# This is a markdown
## That supports HTML
### And it makes things unsafe 
<img onerror="alert('This is a injected script')" src="hacked"/>
```

**Comment by lon-yang** [comment]
Please refer to https://github.com/lon-yang/ngx-markdown-editor/issues/93

**Comment by TiagoJacobs** [comment]
Helllo, thank. you very much... However I don't believe in "sanitizing".

I would prefer that we can completely disable HTML.

Something that would:

1 - process the "htmlentities" - replace all `<` by `&lt;`, `>` by `&gt;`, ...
2 - process markdown

This way we ensure no HTML tag is processed.

Is this possible?

**Comment by lon-yang** [comment]
![image](https://user-images.githubusercontent.com/9428909/162552405-a8c410bf-6016-4660-b0c5-241a040fdf9f.png)

In the `preRender` function, you can replace the content that you want to

https://github.com/lon-yang/ngx-markdown-editor#options
