### ISSUE TITLE
in editor mode always has a printMarginLine

### ISSUE THREAD

**Issue by scobiser2** [lon-yang/ngx-markdown-editor#118]
when in editor mode,the editor area always has a printMarginLine, we can extend the options , add a showPrintMargin attribute to control whether the line shows in the ui, in the ace-editor example, it  uses
`    editor.setOption(showPrintMargin,false)
`
to hide it.

**Comment by lon-yang** [comment]
Have you try this https://ajaxorg.github.io/ace-api-docs/classes/Ace.Editor.html#setShowPrintMargin
```ts
editor.setShowPrintMargin(false)
```

**Comment by scobiser2** [comment]
the MarkdownEditorComponent can not access the editor attribute, it is a private attribute _aceEditorIns
