### ISSUE TITLE
Feature Request:  Pre-render hook

### ISSUE THREAD

**Issue by JohnArrowwood** [lon-yang/ngx-markdown-editor#13]
I need to be able to hook into the preview of the contents, and interpolate values before the Markdown is interpreted.  

For example, if the contents looks something like this:

    This is my little document, and {{variable}} 
    should be replaced with the contents of `variable`

Then I want the value of `{{variable}}` to be interpolated to `<span class=variable-value>theValue</span>` before the Markdown processing begins.

I'd like to request the ability to specify `[preRender]="myFilter"` to have my function called on the value of the markdown text prior to passing it to the markdown renderer.

**Comment by lon-yang** [comment]
I will consider this carefully.

**Comment by lon-yang** [comment]
I will support this feature soon

**Comment by lon-yang** [comment]
@JohnArrowwood Please use `ngx-makdown-editor@1.1.6`
Usage: 

`[preRender]="preRender"`
```js
preRender(content) {
    return (content || '').replace(/Taks/g, 'dasdad');
}
```
