### ISSUE TITLE
There is an extra dividing line in the edit box

### ISSUE THREAD

**Issue by patui** [lon-yang/ngx-markdown-editor#149]
![line](https://github.com/instance-oom/ngx-markdown-editor/assets/3607466/4834488a-a870-4075-b609-ffd84c4565f4)

Thank you very much to the author for making such a good project. I encountered such a situation while using it yesterday.

**Comment by instance-oom** [comment]
It's editor's print-margin line.
If you want to hidden this line, you can handle it in `onEditorLoaded` like this
```html
<md-editor (onEditorLoaded)="onEditorLoaded($event)"></md-editor>
```
```ts
onEditorLoaded(editor) {
  editor.setShowPrintMargin(false);
}
```

**Comment by patui** [comment]
thank you very much。

**Comment by bohrasankalp** [comment]
` editor.setShowPrintMargin(false);` this method is not available?
