### ISSUE TITLE
How can i get current cursor position in editor?

### ISSUE THREAD

**Issue by nishishah-inventyv** [lon-yang/ngx-markdown-editor#154]
i wnt to get current cursor position, to enter the text

**Comment by instance-oom** [comment]
Store the ace editor instance in `onEditorLoaded` event.
Then call `editor.getCursorPosition()` will return you the point detail like this
![image](https://github.com/instance-oom/ngx-markdown-editor/assets/9428909/94eab0f3-a87d-4287-931c-5196b0ee608b)

https://ace.c9.io/api/classes/src_editor.Editor.html#getCursorPosition
