### ISSUE TITLE
How to make resizer

### ISSUE THREAD

**Issue by smartHasmukh** [lon-yang/ngx-markdown-editor#18]
I want to make editor resizer but it doesn't make so can you help me with

Thank you in advance

**Comment by lon-yang** [comment]
Sorry. Are you meaning how to trigger the editor resize function or just set the width and height of this editor?

**Comment by lon-yang** [comment]
I'm not very clear about the problem you have encountered. So is that you want to reset the width and height for this editor? Or just want to listen the resize event?
