### ISSUE TITLE
Link is not clickable in preview panel

### ISSUE THREAD

**Issue by BojanJakic** [lon-yang/ngx-markdown-editor#22]
`<a href="some_url>` element is created successfully in preview panel but after click on it - nothing happens

**Comment by BojanJakic** [comment]
![screenshot from 2018-12-05 10-35-04](https://user-images.githubusercontent.com/13537679/49504224-87549a00-f879-11e8-8790-db4800a57972.png)

**Comment by lon-yang** [comment]
Yes, I have added a click listener on the preview panel to stop click in the panel to prevent security issue. But if needed, I can add on option to disable this feature.

**Comment by lon-yang** [comment]
I have add an option `enablePreviewContentClick` to control this feature in `1.1.9`. Please note.
