### ISSUE TITLE
Intercept editor button clicks

### ISSUE THREAD

**Issue by willkara** [lon-yang/ngx-markdown-editor#24]
Is it possible to intercept button clicks in the editor? I was hoping to host my photos in S3 and was thinking I could try and intercept the photo button click. Then I'd handle the uploads in my own fashion and return the URL to use in the editor.

Click button > call intercepted and file uploaded > URL returned > inserted into photo markdown template.

Thoughts?

**Comment by lon-yang** [comment]
My plan is to implement the feature similar to `Github`. We can dragging & dropping or pasting from the clipboard, then i will call the upload function that you defined on the component to get the final url. And this feature is in processing.

**Comment by willkara** [comment]
@lon-yang sounds exactly what I'd like. Let me know if you want me to look into anything!

**Comment by lon-yang** [comment]
@willkara I have released 1.1.10. And this verion has the `input` named `upload`. Please check the options in [README.md](https://github.com/lon-yang/ngx-markdown-editor) or see the [demo code](https://github.com/lon-yang/ngx-markdown-editor/blob/master/demo/src/app/app.component.ts#L50-L64).
