### ISSUE TITLE
new line with Enter key do not work

### ISSUE THREAD

**Issue by Portekoi** [lon-yang/ngx-markdown-editor#25]
Maybe I have miss something but when I use `Enter` key to add a new line, it's not working : 

![image](https://user-images.githubusercontent.com/1560754/50831936-de540000-134c-11e9-8761-d1a269387c97.png)

Is there an option to enable this?

**Comment by lon-yang** [comment]
I think this is the [markedjs](https://github.com/markedjs/marked) libraries render style. If you want to add a new line, please add two space or tab space before you press the `Enter` key.

**Comment by lon-yang** [comment]
The [markedjs](https://github.com/markedjs/marked) library has one option can enable this feature. Unfortunately, this component does not yet provide the ability to set this option.
But I will add this as soon as possible.

**Comment by lon-yang** [comment]
Please use `1.1.11`. Then setting the `markedjsOpt` on the `options`. 
e.g.
```ts
public options: MdEditorOption = {
  markedjsOpt: {
    breaks: true
  }
};
```

**Comment by Portekoi** [comment]
Awesome, Thank you !
