### ISSUE TITLE
MisMatch version with WebPack

### ISSUE THREAD

**Issue by Portekoi** [lon-yang/ngx-markdown-editor#26]
I've intalled your package and my server was already running.

I've stop it and try to restart and I have this error now : 

```
ERROR in Metadata version mismatch for module project/node_modules/ngx-markdown-editor/ngx-markdown-editor.d.ts, found version 4, expected 3, resolving symbol ProjectEventPostModule in Project/src/app/shared/project/event-post/project-event-post.module.ts, resolving symbol ProjectEventPostModule in Project/src/app/shared/project/event-post/project-event-post.module.ts
```

I've deleted the node_modules folder but I still have this error.

**Comment by Portekoi** [comment]
Version 1.1.6 is working. With version 1.1.7, I have the error.

**Comment by lon-yang** [comment]
Have you deleted `package-lock.json` when you delete the `node_modules` folder?

**Comment by Portekoi** [comment]
I've just give a try and I still have the same error.

When I run a `npm start`, I get the error but if I update a file and save it, the error disappear. 

But I always get it when I try to build it... : 

`
![image](https://user-images.githubusercontent.com/1560754/50868937-2a855b80-13b2-11e9-998f-a6ce6b02ebe8.png)

**Comment by lon-yang** [comment]
Is angular library version too low? Which angular version are you using?

**Comment by Portekoi** [comment]
It's a huge project running under Angular 4. 

But again, `npm start` give me the issue but when I update a file, the error disappears. 

Just take a look to this video, I show you this : 
https://www.youtube.com/watch?v=NzPkM7f1v-g

**Comment by lon-yang** [comment]
Maybe the angular version is the reason for this issue. Because this library using the latest `ng-packagr` tool for build. And then this tool generate a metadata.json(Angular Package Format) for aot, but the version is `v4` not `v3`. Unfortunately, metadata v4 cannot be used with Angular 4.

Please sea this [issue](https://github.com/ng-packagr/ng-packagr/issues/705)

**Comment by Portekoi** [comment]
I've no solution with this. There no solution to downgrade `ng-packagr` in this in this package?

Angular 4 is a major version and it's used in many projects at this time.

**Comment by lon-yang** [comment]
Myabe you can fork this repo, then downgrade `ng-packager` and `angular`. Or just use the source code.

**Comment by Portekoi** [comment]
Thanks for your help ! I'll use the source code and tell you if it's working. Thanks again.
