### ISSUE TITLE
Resize the textarea

### ISSUE THREAD

**Issue by Portekoi** [lon-yang/ngx-markdown-editor#27]
How can I enable the option to resize the textarea like in GitHub ?

Add in the bottom right corner somethind to give this option to my visitor : 
![image](https://user-images.githubusercontent.com/1560754/51075551-395b5f00-168d-11e9-9fbd-dea2aa9a0cde.png)

Thanks again !

**Comment by lon-yang** [comment]
There is no option to enable the resize feature at now. I will handle it later. Sorry for that.

**Comment by lon-yang** [comment]
Please upgrade to `1.2.0`. Then set the `resizable` option to true at `options`.
