### ISSUE TITLE
Autoscale height of MD-Editor to fit content

### ISSUE THREAD

**Issue by KingDarBoja** [lon-yang/ngx-markdown-editor#28]
Hello,

I want to make this markdown editor to fit to the content being displayed so I can place it on a webpage.
I checked the docs and so far there is a  fixed height for the editor if not provided (300px). I tried autoscaling using the viewport height but no success.

Cheers!

**Comment by lon-yang** [comment]
Yeah. It is not supported now. I will try my best to solve this problem. Thanks.

**Comment by lon-yang** [comment]
Sorry it took so long. I tried to use `height="calc(100vh - 100px)"`, and it's working. Is this what you need?

**Comment by KingDarBoja** [comment]
> Sorry it took so long. I tried to use `height="calc(100vh - 100px)"`, and it's working. Is this what you need?

Haven't tested it yet, if anything I will tag you in this conversation 😄

**Comment by lon-yang** [comment]
This issue will be closed. If need, please reopen it.
