### ISSUE TITLE
[Security Issue] JavaScript Execution using link

### ISSUE THREAD

**Issue by h33raj** [lon-yang/ngx-markdown-editor#29]
When we enter:

![image](https://user-images.githubusercontent.com/9161506/52759093-a4f66a80-3045-11e9-81c0-731ad7d37a01.png)

I am able to execute alert(1) in Javascript, which may lead to cross site scripting. Any Fix!!

**Comment by lon-yang** [comment]
Have you diabled the `enablePreviewContentClick` option?

**Comment by lon-yang** [comment]
This issue will be closed. If need, please reopen it.

**Comment by h33raj** [comment]
What if  the Javascript:URI is right clicked and open in another tab. It executes XSS

**Comment by apetushkov** [comment]
Yeah, also works for handlers like
<img src="1" onerror="alert(1)">
