### ISSUE TITLE
How can we have markdown viewer only

### ISSUE THREAD

**Issue by dyapasrikanth** [lon-yang/ngx-markdown-editor#3]
Want to see only data, not editor. How can we use it like that??

**Comment by lon-yang** [comment]
It's cannot for now. And I'm not sure whether it is necessary

**Comment by dyapasrikanth** [comment]
It can be like GitHub readme, everyone can see it, but logged in users only can edit.

**Comment by lon-yang** [comment]
ok. I will add this feature.
