### ISSUE TITLE
[Error] ERROR – Error: Uncaught (in promise): Error: Template parse errors: 'md-editor' is not a known element:

### ISSUE THREAD

**Issue by corbin88** [lon-yang/ngx-markdown-editor#36]
I'm trying to use this package with Ionic version 4. I'm new to Angular so I'm probably missing a step here as I don't know where to implement the **options** from the readme:

```
{  
  showBorder?: boolean       // Show editor component's border. Default is true
  hideIcons?: Array<string>  // ['Bold', 'Italic', 'Heading', 'Refrence', 'Link', 'Image', 'Ul', 'Ol', 'Code', 'TogglePreview', 'FullScreen']. Default is empty
  scrollPastEnd?: number     // The option for ace editor. Default is 0
  enablePreviewContentClick?: boolean  // Allow user fire the click event on the preview panel, like href etc. Default is false
  resizable?: boolean           // Allow resize the editor
  markedjsOpt?: MarkedjsOption  // The markedjs option, see https://marked.js.org/#/USING_ADVANCED.md#options
}
```

I installed the editor:

`npm i ngx-markdown-editor﻿`

Then I added to my app.module.ts the LMarkDownEditorModule like in the docs:

```
import { LMarkdownEditorModule } from 'ngx-markdown-editor';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    LMarkdownEditorModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
Finally I tried to add the template tag to my settings.page.html:

`<md-editor name="Content"></md-editor>`

Now I'm getting this error:

> [Error] ERROR – Error: Uncaught (in promise): Error: Template parse errors:
> 'md-editor' is not a known element:﻿
> 1. If 'md-editor' is an Angular component, then verify that it is part of this module.
> 2. If 'md-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
>     <ion-item [routerLink]="['/','passcode']">
>       <ion-label>Setup passcode</ion-label>
>       [ERROR ->]<md-editor name="Content" >
> </md-editor>
>     </ion-item>
> "): ng:///SettingsPageModule/SettingsPage.html@13:6
> 'md-editor' is not a known element:
> 1. If 'md-editor' is an Angular component, then verify that it is part of this module.
> 2. If 'md-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
>     <ion-item [routerLink]="['/','passcode']">
>       <ion-label>Setup passcode</ion-label>
>       [ERROR ->]<md-editor name="Content" >
> </md-editor>
>     </ion-item>
> "): ng:///SettingsPageModule/SettingsPage.html@13:6
> syntaxError@ionic://localhost/vendor.js:11068:22
> parse@ionic://localhost/vendor.js:29243:30
> _compileTemplate@ionic://localhost/vendor.js:34796:37
> forEach@[native code]
> _compileComponents@ionic://localhost/vendor.js:34739:26
> ionic://localhost/vendor.js:34649:37
> compileModuleAsync@ionic://localhost/vendor.js:34608:64
> onInvoke@ionic://localhost/vendor.js:53422:39
> run@ionic://localhost/polyfills.js:2512:49
> ionic://localhost/polyfills.js:3251:37
> onInvokeTask@ionic://localhost/vendor.js:53413:43
> runTask@ionic://localhost/polyfills.js:2557:57
> drainMicroTaskQueue@ionic://localhost/polyfills.js:2963:42
> invokeTask@ionic://localhost/polyfills.js:2864:40
> invokeTask@ionic://localhost/polyfills.js:4106:20
> globalZoneAwareCallback@ionic://localhost/polyfills.js:4143:31
> Error: Uncaught (in promise): Error: Template parse errors:
> 'md-editor' is not a known element:
> 1. If 'md-editor' is an Angular component, then verify that it is part of this module.
> 2. If 'md-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
>     <ion-item [routerLink]="['/','passcode']">
>       <ion-label>Setup passcode</ion-label>
>       [ERROR ->]<md-editor name="Content" >
> </md-editor>
>     </ion-item>
> "): ng:///SettingsPageModule/SettingsPage.html@13:6
> 'md-editor' is not a known element:
> 1. If 'md-editor' is an Angular component, then verify that it is part of this module.
> 2. If 'md-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
>     <ion-item [routerLink]="['/','passcode']">
>       <ion-label>Setup passcode</ion-label>
>       [ERROR ->]<md-editor name="Content" >
> </md-editor>
>     </ion-item>
> "): ng:///SettingsPageModule/SettingsPage.html@13:6
> syntaxError@ionic://localhost/vendor.js:11068:22
> parse@ionic://localhost/vendor.js:29243:30
> _compileTemplate@ionic://localhost/vendor.js:34796:37
> forEach@[native code]
> _compileComponents@ionic://localhost/vendor.js:34739:26
> ionic://localhost/vendor.js:34649:37
> compileModuleAsync@ionic://localhost/vendor.js:34608:64
> onInvoke@ionic://localhost/vendor.js:53422:39
> run@ionic://localhost/polyfills.js:2512:49
> ionic://localhost/polyfills.js:3251:37
> onInvokeTask@ionic://localhost/vendor.js:53413:43
> runTask@ionic://localhost/polyfills.js:2557:57
> drainMicroTaskQueue@ionic://localhost/polyfills.js:2963:42
> invokeTask@ionic://localhost/polyfills.js:2864:40
> invokeTask@ionic://localhost/polyfills.js:4106:20
> globalZoneAwareCallback@ionic://localhost/polyfills.js:4143:31resolvePromise — zone.js:831resolvePromise — zone.js:788(anonymous function) — zone.js:892onInvokeTask — core.js:17290runTask — zone.js:195drainMicroTaskQueue — zone.js:601invokeTask — zone.js:502invokeTask — zone.js:1744globalZoneAwareCallback — zone.js:1781
>     defaultErrorLogger (vendor.js:51847)
>     handleError (vendor.js:51895)
>     next (vendor.js:53894:140)
>     (anonymous function) (vendor.js:49638)
>     __tryOrUnsub (vendor.js:85429)
>     next (vendor.js:85367)
>     _next (vendor.js:85313)
>     next (vendor.js:85290)
>     next (vendor.js:85056)
>     emit (vendor.js:49622)
>     run (polyfills.js:2512)
>     onHandleError (vendor.js:53444)
>     runGuarded (polyfills.js:2526)
>     _loop_1 (polyfills.js:3056)
>     microtaskDrainDone (polyfills.js:3065)
>     drainMicroTaskQueue (polyfills.js:2970)
>     invokeTask (polyfills.js:2864)
>     invokeTask (polyfills.js:4106)
>     globalZoneAwareCallback (polyfills.js:4143)

I can't tell if this is an actual error or a misstep on my behalf due to lack of competence with angular. Thanks for any help I get.

**Comment by lon-yang** [comment]
Can you paste your `app.module.ts` code on there ?

**Comment by lon-yang** [comment]
I will colse this issue, If you want another issue, please reopen it or create new one.

**Comment by sakenk** [comment]
@corbin88 hi did you resolve issue? i have exactly the same problem

**Comment by sakenk** [comment]
> I'm trying to use this package with Ionic version 4. I'm new to Angular so I'm probably missing a step here as I don't know where to implement the **options** from the readme:
> 
> ```
> {  
>   showBorder?: boolean       // Show editor component's border. Default is true
>   hideIcons?: Array<string>  // ['Bold', 'Italic', 'Heading', 'Refrence', 'Link', 'Image', 'Ul', 'Ol', 'Code', 'TogglePreview', 'FullScreen']. Default is empty
>   scrollPastEnd?: number     // The option for ace editor. Default is 0
>   enablePreviewContentClick?: boolean  // Allow user fire the click event on the preview panel, like href etc. Default is false
>   resizable?: boolean           // Allow resize the editor
>   markedjsOpt?: MarkedjsOption  // The markedjs option, see https://marked.js.org/#/USING_ADVANCED.md#options
> }
> ```
> 
> I installed the editor:
> 
> `npm i ngx-markdown-editor﻿`
> 
> Then I added to my app.module.ts the LMarkDownEditorModule like in the docs:
> 
> ```
> import { LMarkdownEditorModule } from 'ngx-markdown-editor';
> 
> @NgModule({
>   declarations: [
>     AppComponent
>   ],
>   imports: [
>     BrowserModule,
>     FormsModule,
>     LMarkdownEditorModule
>   ],
>   providers: [],
>   bootstrap: [AppComponent]
> })
> export class AppModule { }
> ```
> 
> Finally I tried to add the template tag to my settings.page.html:
> 
> `<md-editor name="Content"></md-editor>`
> 
> Now I'm getting this error:
> 
> > [Error] ERROR – Error: Uncaught (in promise): Error: Template parse errors:
> > 'md-editor' is not a known element:﻿
> > 
> > 1. If 'md-editor' is an Angular component, then verify that it is part of this module.
> > 2. If 'md-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
> >    <ion-item [routerLink]="['/','passcode']">
> >    Setup passcode
> >    [ERROR ->]
> > 
> > 
> >     
> > "): ng:///SettingsPageModule/SettingsPage.html@13:6
> > 'md-editor' is not a known element:
> > 1. If 'md-editor' is an Angular component, then verify that it is part of this module.
> > 2. If 'md-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
> >     
> >       Setup passcode
> >       [ERROR ->]
> > 
> >     
> > "): ng:///SettingsPageModule/SettingsPage.html@13:6
> > syntaxError@ionic://localhost/vendor.js:11068:22
> > parse@ionic://localhost/vendor.js:29243:30
> > _compileTemplate@ionic://localhost/vendor.js:34796:37
> > forEach@[native code]
> > _compileComponents@ionic://localhost/vendor.js:34739:26
> > ionic://localhost/vendor.js:34649:37
> > compileModuleAsync@ionic://localhost/vendor.js:34608:64
> > onInvoke@ionic://localhost/vendor.js:53422:39
> > run@ionic://localhost/polyfills.js:2512:49
> > ionic://localhost/polyfills.js:3251:37
> > onInvokeTask@ionic://localhost/vendor.js:53413:43
> > runTask@ionic://localhost/polyfills.js:2557:57
> > drainMicroTaskQueue@ionic://localhost/polyfills.js:2963:42
> > invokeTask@ionic://localhost/polyfills.js:2864:40
> > invokeTask@ionic://localhost/polyfills.js:4106:20
> > globalZoneAwareCallback@ionic://localhost/polyfills.js:4143:31
> > Error: Uncaught (in promise): Error: Template parse errors:
> > 'md-editor' is not a known element:
> > 1. If 'md-editor' is an Angular component, then verify that it is part of this module.
> > 2. If 'md-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
> >     
> >       Setup passcode
> >       [ERROR ->]
> > 
> >     
> > "): ng:///SettingsPageModule/SettingsPage.html@13:6
> > 'md-editor' is not a known element:
> > 1. If 'md-editor' is an Angular component, then verify that it is part of this module.
> > 2. If 'md-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
> >     
> >       Setup passcode
> >       [ERROR ->]
> > 
> >     
> > "): ng:///SettingsPageModule/SettingsPage.html@13:6
> > syntaxError@ionic://localhost/vendor.js:11068:22
> > parse@ionic://localhost/vendor.js:29243:30
> > _compileTemplate@ionic://localhost/vendor.js:34796:37
> > forEach@[native code]
> > _compileComponents@ionic://localhost/vendor.js:34739:26
> > ionic://localhost/vendor.js:34649:37
> > compileModuleAsync@ionic://localhost/vendor.js:34608:64
> > onInvoke@ionic://localhost/vendor.js:53422:39
> > run@ionic://localhost/polyfills.js:2512:49
> > ionic://localhost/polyfills.js:3251:37
> > onInvokeTask@ionic://localhost/vendor.js:53413:43
> > runTask@ionic://localhost/polyfills.js:2557:57
> > drainMicroTaskQueue@ionic://localhost/polyfills.js:2963:42
> > invokeTask@ionic://localhost/polyfills.js:2864:40
> > invokeTask@ionic://localhost/polyfills.js:4106:20
> > globalZoneAwareCallback@ionic://localhost/polyfills.js:4143:31resolvePromise — zone.js:831resolvePromise — zone.js:788(anonymous function) — zone.js:892onInvokeTask — core.js:17290runTask — zone.js:195drainMicroTaskQueue — zone.js:601invokeTask — zone.js:502invokeTask — zone.js:1744globalZoneAwareCallback — zone.js:1781
> >     defaultErrorLogger (vendor.js:51847)
> >     handleError (vendor.js:51895)
> >     next (vendor.js:53894:140)
> >     (anonymous function) (vendor.js:49638)
> >     __tryOrUnsub (vendor.js:85429)
> >     next (vendor.js:85367)
> >     _next (vendor.js:85313)
> >     next (vendor.js:85290)
> >     next (vendor.js:85056)
> >     emit (vendor.js:49622)
> >     run (polyfills.js:2512)
> >     onHandleError (vendor.js:53444)
> >     runGuarded (polyfills.js:2526)
> >     _loop_1 (polyfills.js:3056)
> >     microtaskDrainDone (polyfills.js:3065)
> >     drainMicroTaskQueue (polyfills.js:2970)
> >     invokeTask (polyfills.js:2864)
> >     invokeTask (polyfills.js:4106)
> >     globalZoneAwareCallback (polyfills.js:4143)
> 
> I can't tell if this is an actual error or a misstep on my behalf due to lack of competence with angular. Thanks for any help I get.

hi did you resolve issue? i have exactly the same problem

**Comment by sakenk** [comment]
@corbin88 hi did you resolve issue? i have the same problem
