### ISSUE TITLE
how to set image upload url

### ISSUE THREAD

**Issue by mikeycoxon** [lon-yang/ngx-markdown-editor#37]
I have a locally-served angular project, which connects to AWS API Gateway, and, ultimately, to an S3 bucket.

in attempting to add image (or file) upload capabilities, I am finding that while I can set the reference url (that is put into the page), I don't know how to set the upload location (the place where the file is supposed to go on the server).

I followed your demo code

```
doUpload(files: Array<File>): Promise<Array<UploadResult>> {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        const result: Array<UploadResult> = [];
        for (const file of files) {
          console.log(file);
          result.push({
            name: file.name,
            url: `${environment.blogContentUrl}/posts${window.location.href.substring(window.location.href.lastIndexOf('/'))}/assets/${file.name}`,
            isImg: file.type.indexOf('image') !== -1
          });
        }
        resolve(result);
      }, 3000);
    });
  }
```
This sets the correct reference url in the page edit:
```
![4constraints.png](https://blogcdkstack-blogstorexxxxxxxx-kj0hdxxxxxrh.s3-ap-southeast-2.amazonaws.com/posts/the-4-constraints-of-project-management/assets/4constraints.png)
```
but looking in the console, there doesn't appear to be any upload happening (no posts for this data).

I realise that there is something obvious that I'm missing, could you let me know what that is?

**Comment by lon-yang** [comment]
It's need you upload file to S3 by yourself with http or someothers. When file is upload succeed, just give me the result like 
```js
[
  {
    "name": xxx,
    "url": xxx,
    "isImg": true
  }
]
```

**Comment by mikeycoxon** [comment]
Thanks for the fast answer.

Yes, I figured so, unfortunately all angular injected references are 'undefined' inside `doUpload(files: Array<File>)` so I cannot see any way of performing the upload via HttpClient. I tried for example:

```
doUpload(files: Array<File>): Promise<Array<UploadResult>> {
    const service: PostContentService = this.postContentService;
    console.log(service);
    return new Promise((resolve, reject) => {
      const pointer = window.location.href.substring(window.location.href.lastIndexOf('/'));
      setTimeout(() => {
        const result: Array<UploadResult> = [];
        for (const file of files) {
          console.log(file);
          result.push({
            name: file.name,
            url: `${environment.blogContentUrl}/posts${pointer}/assets/${file.name}`,
            isImg: file.type.indexOf('image') !== -1
          });
        }
        service.uploadAsset(new Set(files), pointer);
        resolve(result);
      }, 3000);
    });
  }
```
but `console.log(service);` is undefined. Now, in angular, they recommend injecting the HttpClient, but of course, the injector, itself, is also out of scope.

So, I'm having trouble seeing how i can upload it myself.

**Comment by lon-yang** [comment]
Please try this in the constrictor function. 
```js
constructor() {
  this. doUpload = this. doUpload. bind(this);
}
```

**Comment by lon-yang** [comment]
I will close this issue. If you still confused, please comment or reopen this.

**Comment by mikeycoxon** [comment]
Thanks for you help. Yes, the code works now

**Comment by DerekFangming** [comment]
@lon-yang I have the same problem. Can you post your code also in the wiki so that people knows?

**Comment by lon-yang** [comment]
@DerekFangming I have already updated the README.md
