### ISSUE TITLE
UI buttons not removing markdown syntax if they present

### ISSUE THREAD

**Issue by dyapasrikanth** [lon-yang/ngx-markdown-editor#4]
When I click on UI buttons it is adding syntax but they are not working to remove existing syntax.

Can we have this feature??

**Comment by lon-yang** [comment]
I will consider your suggestion carefully.

**Comment by lon-yang** [comment]
I think this feature will not be able. Because I don't know that whether you want to remove it. And like github, it won't remove the existing syntax.
