### ISSUE TITLE
Install dependencies using npm instead of bootcss.com

### ISSUE THREAD

**Issue by bartdebever** [lon-yang/ngx-markdown-editor#41]
In my experience during this day, the cdn.bootcss.com website is incredibly slow, taking the editors minutes to load. It would be more convenient to load the dependencies over npm or support another local source.

A developer could download these dependencies and add them manually, yet it would be easier to include them in the npm package or give documentation on where to download these dependencies.

**Comment by lon-yang** [comment]
The `2.1.0` has changed. Please see [README.md](https://github.com/lon-yang/ngx-markdown-editor/blob/master/README.md)
