### ISSUE TITLE
Scroll Option for preview mode

### ISSUE THREAD

**Issue by KingDarBoja** [lon-yang/ngx-markdown-editor#42]
Hi again, I just noticed that the preview section doesn't have a scroll option but the editor one does.

It is possible to fix the layout so the preview section can be scrolled like as the editor one? This is happening on the latest version (2.1.0) and it can be seen on the demo too.

Cheers!

**Comment by lon-yang** [comment]
Are you meaning the `scrollPastEnd` option?

**Comment by KingDarBoja** [comment]
> Are you meaning the `scrollPastEnd` option?

Not sure what is the purpose of that option, what I do mean is being able to keep the preview section with independent scroll from the editor one. For some reason it isn't working on the demo as you can see:

![image](https://user-images.githubusercontent.com/30560560/63112803-c5e93b00-bf56-11e9-8afc-3066379a637a.png)

Also, the editor section line (right side) gets cut at some height, maybe that is related to the scroll not being taken into account?

**Comment by KingDarBoja** [comment]
@lon-yang After checking the source code and making few edits to the `.scss` file, got the desired result:

![image](https://user-images.githubusercontent.com/30560560/63120507-03a28f80-bf68-11e9-9e82-23ccee6eb675.png)

Shall I make a PR with this change? Or if you wish, you can check my local [branch](https://github.com/KingDarBoja/ngx-markdown-editor/tree/feature/independent-scroll-y)

**Comment by lon-yang** [comment]
@KingDarBoja I has release `2.1.1` to solve this issue.

**Comment by KingDarBoja** [comment]
@lon-yang Awesome! I will test it as soon as possible. Loved your library 🍰 

Cheers!
