### ISSUE TITLE
Disable preview mode

### ISSUE THREAD

**Issue by ashefor** [lon-yang/ngx-markdown-editor#43]
Is there a way to disable preview mode on editor initialisation? I only want preview mode to be seen when I click the show preview icon button and not to be shown by default.

**Comment by lon-yang** [comment]
Sorry, there is no way to disable preview mode on editor init. But I think i can open up this parameter.

**Comment by ashefor** [comment]
okay I will wait for the update. that'd be very nice. thank you

**Comment by lon-yang** [comment]
Please upgrade to `2.1.2`. Then `options` setting has a `showPreviewPanel` property. Default is `true`, you can set it to `false` on init.

**Comment by ashefor** [comment]
thank you!
