### ISSUE TITLE
Large image is not resized within the editor (preview mode)

### ISSUE THREAD

**Issue by DerekFangming** [lon-yang/ngx-markdown-editor#44]
Hi, there. When I'm trying to put in a large image (pixel size) into the editor, it squeeze down the textarea until it's completely gone. Take this image for example https://i.imgur.com/22PMF8I.jpg

![Capture](https://user-images.githubusercontent.com/7002697/65210205-0a895a00-da60-11e9-84bd-e9b8003faf10.PNG)

Note that the horizontal scroll bar is already in left most position. Is there a way to instead scale the image to fit the preview window size (width, and keep the ratio ofc)?

Thanks!

**Comment by lon-yang** [comment]
Please upgrade to `2.1.3`.
