### ISSUE TITLE
when making form bigger the vertical line appears inside of the form

### ISSUE THREAD

**Issue by sakenk** [lon-yang/ngx-markdown-editor#49]
![image](https://user-images.githubusercontent.com/16571508/65762171-2f598d80-e142-11e9-870a-ee57ff745cc0.png)

**Comment by lon-yang** [comment]
This line just the editor's print-margin line. I think it's irrelevant.

**Comment by sakenk** [comment]
do you how to fix it?

**Comment by lon-yang** [comment]
It's not a bug, I don't think it has to be fixed. It's the editor's feature.
