### ISSUE TITLE
Preview in realtime at editor

### ISSUE THREAD

**Issue by ruslanguns** [lon-yang/ngx-markdown-editor#50]
First of all, thanks for contributing us with this project, is really nice.

I am looking a way to show the preview on top of what is being written. 

Is it possible?

**Comment by lon-yang** [comment]
sorry, I think this is impossible.

**Comment by ruslanguns** [comment]
Please have a look into the ckeditor demo

https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html

At the moment you are inserting text it previews the written format.

**Comment by lon-yang** [comment]
I think the ckeditor's demo is meaing you written richtext then it will give you the markdown output.
And this component is using ace editor not ckeditor.

**Comment by ruslanguns** [comment]
Ok understood. Thanks for response, I very appreciate
