### ISSUE TITLE
Table highlighting

### ISSUE THREAD

**Issue by roidlringo** [lon-yang/ngx-markdown-editor#52]
Hi 
In your example the following text renders a table in the preview:
```
 Name | Type
 ---- | ----
 A | Test
```
Alle Specs that i could find like Jira or GFM looks like:
```
 |Name | Type|
 |---- | ----|
 |A | Test|
```
After setting the marked.js options like 
```
public editorOption = {
    hideIcons: ['Refrence', 'Link', 'Image', 'TogglePreview', 'FullScreen'],
    resizable: false,
    markedjsOpt: {
      gfm: true,
    }
  };
```

Table will again not renderd correctly.

Is this my mistake ?

Ringo

**Comment by lon-yang** [comment]
I tried this, but this render as normal. [Online Demo](https://stackblitz.com/edit/angular-fayrzm)
