### ISSUE TITLE
Additional options of Ace Editor

### ISSUE THREAD

**Issue by godardth** [lon-yang/ngx-markdown-editor#55]
Hi,

Is there a way to configure the ace editor with all the options documented here : https://github.com/ajaxorg/ace/wiki/Configuring-Ace

For example, I would like to disable the line numbers with that option:
`showLineNumbers: boolean (defaults to true)`

Thanks for this nice project !

**Comment by lon-yang** [comment]
I will add an output for this and pass the editor instance to you. Then you can change option by yourself.

**Comment by godardth** [comment]
Sounds great ! Thanks

**Comment by lon-yang** [comment]
Hi @godardth .
Please upgrade to `2.5.0`. Then using `onEditorLoaded` event to get the editor instance.

**Comment by godardth** [comment]
Thanks ! Great addition :)

**Comment by PhilipAllStar** [comment]
Outside of the on editor loaded function I am always getting an undefined. How do I access the instance outside of that method?

**Comment by lon-yang** [comment]
Can you paste some example code in here?

**Comment by PhilipAllStar** [comment]
`  ngOnInit() {
    this.loadContent(this.answerText);
    this.editor.setOption('readonly', true);
      }`

`  onEditorLoaded(editor) {
    console.log(`ACE Editor Ins: `, editor);
    this.editor = editor;
  }`

**Comment by PhilipAllStar** [comment]
I found the mistake myself: The `onEditorLoaded` method gets called AFTER the `ngOnInit` method. That was why I was getting an undefined. 
Thanks and sorry for the trouble.
