### ISSUE TITLE
ReadOnly option

### ISSUE THREAD

**Issue by thedigitaljedi86** [lon-yang/ngx-markdown-editor#57]
Is it possible to set the editor in "readonly mode" or can I just use preview mode and remove the toolbar?

**Comment by lon-yang** [comment]
Listen the `onEditorLoaded` event, and you will get the editor instance, then you can config the editor by your self. https://github.com/ajaxorg/ace/wiki/Configuring-Ace
```html
<md-editor name="Content" onEditorLoaded="onEditorLoaded($event)"></md-editor>
```
```ts
onEditorLoaded(editor) {
  editor.setOption('readOnly', true);
}
```


Preview mode and remove the toolbar, jut set the `mode` and `hideToolbar` option
```html
<md-editor mode="preview" [hideToolbar]="true"></md-editor>
```

**Comment by thedigitaljedi86** [comment]
Hi!

Thx for the quick reply! I will give it a try.

Best regards
Nikolaj

Den ons. 19. feb. 2020 kl. 14.37 skrev Lon <notifications@github.com>:
