### ISSUE TITLE
Characters overlap when typing using Japanese and Chinese keyboard input on IE11

### ISSUE THREAD

**Issue by com77001** [lon-yang/ngx-markdown-editor#59]
![image](https://user-images.githubusercontent.com/47674814/78053885-11a9f280-7336-11ea-9f98-cf4dbe800962.png)

Error: When I'm typing Japanese or Chinese characters the displayed characters would overlap. In the Chinese keyboard case, the pinyin would overlap. However, the overlap disappears after hitting the "Enter" key (after confirming the input characters as you would with using a Japanese or Chinese keyboard).

Browser: IE11  
OS: Windows 10

**Comment by lon-yang** [comment]
https://github.com/lon-yang/ngx-markdown-editor/issues/60
