### ISSUE TITLE
Line Separator character shows at the beginning of the line on Chrome when typing in Chinese or Japanese

### ISSUE THREAD

**Issue by com77001** [lon-yang/ngx-markdown-editor#60]
![image](https://user-images.githubusercontent.com/47674814/78054908-9d704e80-7337-11ea-9c1a-0f730640eee9.png)

![image](https://user-images.githubusercontent.com/47674814/78055137-ef18d900-7337-11ea-8c9c-4ad5843ac338.png)

Error: A line separator character, (the rectangle that wraps the word "LSEP") shows at the beginning of the line when typing Chinese or Japanese characters. 

Browser: Chrome Version 80.0.3987.149
OS: Windows 10

**Comment by lon-yang** [comment]
I can't reproduce this. It's work fine with the online demo http://lon-yang.github.io/markdown-editor/ in chrome or IE. 

`Chrome (80.0.3987.149):`

![image](https://user-images.githubusercontent.com/9428909/78087334-5c3d7480-73f3-11ea-960a-ce1e6441a5f7.png)


`IE 11:`

![image](https://user-images.githubusercontent.com/9428909/78087311-462fb400-73f3-11ea-8bcd-54993264c3a2.png)

**Comment by lon-yang** [comment]
Can you provide an online demo at https://stackblitz.com? Will be of great help in finding the issue.

**Comment by com77001** [comment]
Hi @Ion-yang, thank you very much for getting back to me.  The screenshots from my examples were actually taken from trying your demo website http://lon-yang.github.io/markdown-editor/  I tried again,and the overlap still appears. I'm trying to get the overlap problem resolved for Japanese, if you try typing in あいうえおきくけこ
日本語日本語 (not through copy and pasting, but typing) you might be able to reproduce the overlapping bug. 

If you look at the IE version in your example, the pinyin seems bolded compared to Chrome version. I think that might be because the pinyin has an overlap that is very close to each other thats why we see the bold.  What do you think?

**Comment by lon-yang** [comment]
Myabe I found the reason. We are using the `brace` library to import ace editor. The latest update of the `brace` library was two years ago. Therefore, this problem is caused by the low version of "ace editor".

I will fix this in the next version, thanks.

**Comment by lon-yang** [comment]
![Annotation 2020-04-08 120726](https://user-images.githubusercontent.com/9428909/78743593-a4c7d580-7991-11ea-803a-c1ce47a6d805.png)

It's normal after upgrade ace editor to latest version. You can import the latest ace editor instead of brace or upgrade `ngx-markdown-editor` to `3.0.0`.

BTW: If you using `3.0.0`, please follow the [README](https://github.com/lon-yang/ngx-markdown-editor) to update your angular project config.
