### ISSUE TITLE
OnRenderFinishedEvent

### ISSUE THREAD

**Issue by ghost** [lon-yang/ngx-markdown-editor#61]
Hi,
Is there a way to get notified when render preview has finished?
I want to run some code post-render that will modified the output in preview.

I tried putting an event on the variable changing, but that changes before output preview has finished rendering.

Ideally something like OnRenderFinishedEvent (similiar to onEditorLoaded)

**Comment by lon-yang** [comment]
I will add this event later, thanks for your feedback.

**Comment by lon-yang** [comment]
Hi @tank104 ,
I want to know if you want to change the HTML source code that generated by markdown? There has an `preRender` input for change the markdown content before reader, maybe I can add a `postRender` input for that.

**Comment by tank104** [comment]
I am already using the prerender - so I tag up the HTML that is renderer.  Once that output has changed and finished rendering I need to run javascript that changes the output again (but needs the complete output to work)

**Comment by tank104** [comment]
unless there is a way I can do it without needing a change from your package?  Sorry I am not too familiar with ACE editor

**Comment by lon-yang** [comment]
It's ok. I will add `postRender` to solve this issue. Like this:
```html
[postRender]="postRender"
```
```ts
constructor() {
  // If you want access `this` in your function. Please add this line.
  this.postRender = this.postRender.bind(this); 
}

postRender(html) {
  // do something to change the html source
  return html;
}
```

I will inform you when it is finished

**Comment by tank104** [comment]
great!  To be clear - this will be called when the DOM Html has changed - i.e. so the scripts we run in this that searches the DOM and makes changes will work on the latest preview.

**Comment by lon-yang** [comment]
Please upgrade to `3.1.0`. 
- [@Input] `postRender`: Change the html souce code generated by marked before update the dom
- [@Output] `onPreviewDomChanged: EventEmitter<HTMLElement>`: Fires when the preview dom updated

**Comment by tank104** [comment]
That worked a treat - legend! Thanks so much  👍 👍 👍
