### ISSUE TITLE
Background and style changes

### ISSUE THREAD

**Issue by Andrusha26** [lon-yang/ngx-markdown-editor#63]
I've not found in documentation is it possible to change background and text color

**Comment by lon-yang** [comment]
Which area's background and text color you want to change?

**Comment by Andrusha26** [comment]
tool panel, an area where I type the text and area where the text is shown.
But it's okay I found the solution, you can inspect and override css with ::ng-deep. The issue is closed, thank you for the reply. I just thought that there is some kind of configs or something like that.

**Comment by Andrusha26** [comment]
I believe it helps somebody
```

::ng-deep{
    .editable-content{
        width: 100%;
        
        .tool-bar {
            background: rgb(129, 129, 129) !important;
        }
        .ace_content{
            background: rgb(63, 63, 63) !important;
            color: white !important;
        }
    
        .preview-panel {
            background: rgb(63, 63, 63) !important;
            color: white !important;
        }
    
        .ace_gutter-layer   {
            background: rgb(63, 63, 63) !important;
            color: white !important;
        }
    }
}

```
