### ISSUE TITLE
Use in combination with Reactive Forms

### ISSUE THREAD

**Issue by Cyberuben** [lon-yang/ngx-markdown-editor#64]
I'm wondering if it's possible to use this library in combination with Reactive Forms, specifically being able to set / get the value using `formControlName` instead of `ngModel`?

If so, how do I achieve this?

**EDIT**

It seems it is possible, however, I do not seem to get any changes made, so it remains `untouched` when changing the content. Is this a bug?

**Comment by lon-yang** [comment]
I don't think so. If you using `setValue` to change the value with no user typing. It will not change the `untouched` status. You can try using `input` control to testing it.

**Comment by Cyberuben** [comment]
The issue is that when actually typing in the markdown editor, so without setValue, it still does not register the input as touched.

**Comment by lon-yang** [comment]
Got it. I will check this issue.

**Comment by lon-yang** [comment]
Please using `3.2.0`

**Comment by Cyberuben** [comment]
I'm afraid this has introduced another bug. If I place my cursor anywhere in the editor and start typing, it automatically moves my cursor to the end of the input, then continues typing there.

[Video of the issue](https://0x.ms/GcGj9kDFwAg)

**Comment by lon-yang** [comment]
Sorry about that. it's already fixed in `3.2.1`
