### ISSUE TITLE
Minor bug with <label> tag

### ISSUE THREAD

**Issue by eau-de-la-seine** [lon-yang/ngx-markdown-editor#65]
Hi, when I encapsulate `<md-editor>` within `<label>` it generates `**Bold Text**` inside the textarea each time I left-click inside the textarea.

```
<label>
  Content
  <md-editor yourParams></md-editor>
</label>
```

**Comment by lon-yang** [comment]
I think it's not a bug. Because you are using the `label` element, and when you click on the label, it will pass the event to inside. Try this:
```html
<label>
  <div style="height: 200px">Click Here</div>
  <button type="button">Not Click Me</button>
</label>
```

If you click on the `div` area, it will fire the button click event too.
