### ISSUE TITLE
problem with angular 10

### ISSUE THREAD

**Issue by sea-kg** [lon-yang/ngx-markdown-editor#69]
ERROR in node_modules/ngx-markdown-editor/lib/md-editor.component.d.ts:1:10 - error TS2724: Module '"../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

**Comment by lon-yang** [comment]
Which version are you using? The `Renderer` has been replaced by `Renderer2` at 96e642d4a11040fa0d3025cec63313fd6e418d3d with version `2.2.0`

**Comment by sea-kg** [comment]
> Which version are you using? The `Renderer` has been replaced by `Renderer2` at [96e642d](https://github.com/lon-yang/ngx-markdown-editor/commit/96e642d4a11040fa0d3025cec63313fd6e418d3d) with version `2.2.0`

was 1.2.0 after update to latest version problem is gone
