### ISSUE TITLE
ERROR ReferenceError: ace is not defined

### ISSUE THREAD

**Issue by doppelgunner** [lon-yang/ngx-markdown-editor#7]
Seems like I can't type anything on the markdown editor and error appears on console.

![image](https://user-images.githubusercontent.com/10264898/29217329-fd0a1ae2-7ee3-11e7-9685-672ecbc4d06e.png)

**Comment by lon-yang** [comment]
This error is meaning you are not add ace library. Are you missing? Or you can type ace in console to check


Best regards
--------------------------
Lon Yang
Email: dove2580@live.com<mailto:dove2580@live.com>

**Comment by doppelgunner** [comment]
Ill check it out some time. But I though in the instruction you pointed out
was to just add script link. I added ace in index.html by using link in the
manual.

**Comment by lon-yang** [comment]
If the script has been added, it should be correct. But if your application js script loaded before than this, it will causing this error, too.

**Comment by doppelgunner** [comment]
Oh sorry so I should add it on the head? Cause I added it after the body
tag. Thanks by the way
