### ISSUE TITLE
[Enhancement Request] Pasting images

### ISSUE THREAD

**Issue by Kp0c** [lon-yang/ngx-markdown-editor#72]
Hi,

Is it possible to paste images via ctrl+V or "Insert" in the right-click menu?
Pasting via Drag&Drop is cool, but in my case, it is common to have an image in the clipboard only.
I think it will be handy to call upload function on the pasting images as well.

Thank you for the cool editor :)

**Comment by lon-yang** [comment]
I will try to find a solution.
