### ISSUE TITLE
No value accessor for form control with name: 'description'

### ISSUE THREAD

**Issue by majkelllo** [lon-yang/ngx-markdown-editor#76]
Hi,

I'm trying to use the component inside reactive form. I have set-up component exactly as per guide but it doesn't appear at all and i see below error in browser console:

`No value accessor for form control with name: 'description'`

If i remove "formControlName" attribute from `md-editor` component it doesn't error but still doesn't render.

I'm using Angular 9.0.6

**Comment by lon-yang** [comment]
https://stackblitz.com/edit/angular-ivy-poqb1g

There is no error. Please give me some detail code for this issue.

**Comment by majkelllo** [comment]
You can close this issue. It was my mistake. I have added markdown to wrong module. Sorry about that
