### ISSUE TITLE
Preview Panel XSS with img tags

### ISSUE THREAD

**Issue by perryflynn** [lon-yang/ngx-markdown-editor#78]
It is possible to inject a XSS into the preview panel because it's renders HTML:

```
<img src="la" onerror="alert('hi');">
```

Reproducable on http://lon-yang.github.io/markdown-editor/

**Comment by lon-yang** [comment]
You can change this option(`markedjsOpt.sanitize`) to `true` to prevent.
e.g.
```ts
options = {
  markedjsOpt: {
    sanitize: true
  }
}
```
```html
<md-editor [options]="options"></md-editor>
```

**Comment by perryflynn** [comment]
> If true, sanitize the HTML passed into markdownString with the sanitizer function.
Warning: This feature is deprecated and it should NOT be used as it cannot be considered secure.
Instead use a sanitize library, like DOMPurify (recommended), sanitize-html or insane on the output HTML!

https://marked.js.org/using_advanced#options

Is it possible to just run the Angular sanirize function on the markdown code first and then parse the markdown? 

https://angular.io/api/platform-browser/DomSanitizer#sanitize

**Comment by lon-yang** [comment]
I will try this or just using `DOMPurify`, then override the sanitize option

**Comment by lon-yang** [comment]
Solved
