### ISSUE TITLE
Support Task Lists 

### ISSUE THREAD

**Issue by bxcodec** [lon-yang/ngx-markdown-editor#8]
Not support task lists as describe here 

https://github.com/blog/1825-task-lists-in-all-markdown-documents

I've tried the demo , but cannot do this

**Comment by lon-yang** [comment]
Are you meaning this?
![default](https://user-images.githubusercontent.com/9428909/29613602-56944962-8839-11e7-8568-02ae66a8b7e8.png)

Or you can see the demo http://lon-yang.github.io/markdown-editor/

BTW: This feature are not supported in current version

**Comment by bxcodec** [comment]
Yes... 
When will be merged ??

**Comment by lon-yang** [comment]
I will publish a new version in today later

**Comment by lon-yang** [comment]
Version 1.1.2 has published
