### ISSUE TITLE
Version 3.3.0 simply doesn't work

### ISSUE THREAD

**Issue by nbittich** [lon-yang/ngx-markdown-editor#80]
updating from 3.2.4 to 3.3.0 simply doesn't work... the readme is either not complete or this release is broken.

**Comment by lon-yang** [comment]
Do you have the error detail?

**Comment by nbittich** [comment]
unfortunately I rolled back my change but if i remember import LMarkdownModule wasn't there anymore.

**Comment by lon-yang** [comment]
That is so sorry. I pushed a wrong package to npm. Please using `3.3.1`, it's already fixed this issue.
