### ISSUE TITLE
Preview model

### ISSUE THREAD

**Issue by Roges93** [lon-yang/ngx-markdown-editor#81]
![image](https://user-images.githubusercontent.com/31095750/105207660-d2fd5700-5b58-11eb-9dc9-dfb3e1438828.png)
Preview panel doesn't work

**Comment by Roges93** [comment]
![image](https://user-images.githubusercontent.com/31095750/105207944-34bdc100-5b59-11eb-8fd0-9b0b59577b2f.png)
![image](https://user-images.githubusercontent.com/31095750/105207991-3edfbf80-5b59-11eb-8b09-e23eff082d93.png)
![image](https://user-images.githubusercontent.com/31095750/105208028-4c954500-5b59-11eb-88fd-b356478e98fd.png)
![image](https://user-images.githubusercontent.com/31095750/105208070-55861680-5b59-11eb-86d5-acddbcd14dc7.png)
![image](https://user-images.githubusercontent.com/31095750/105208089-5c148e00-5b59-11eb-997a-1a04ea75e1ec.png)

**Comment by lon-yang** [comment]
Can you paste the code of `preRender`?

**Comment by Roges93** [comment]
![image](https://user-images.githubusercontent.com/31095750/105502027-031e3480-5cd6-11eb-8e6b-05293be93e9b.png)

**Comment by lon-yang** [comment]
![image](https://user-images.githubusercontent.com/9428909/105563672-fcd19c00-5d59-11eb-9f9e-dfb8c2615bd4.png)
I mean this function

**Comment by lon-yang** [comment]
Please reopen it if you have any update.

**Comment by gabrielmdrd** [comment]
Hello,
I'm facing the same issue, the preview is not working.
You can find my prerender function just below.

```typescript
preRender(mdContent) {
    console.log('preRender fired');
    return mdContent;
}
```

Thank you in advance for your help.

Best Regards,
