### ISSUE TITLE
preview: scrolling "broken" some times

### ISSUE THREAD

**Issue by nbittich** [lon-yang/ngx-markdown-editor#83]
In the latest version (3.3.1), it becomes impossible to scroll the preview  from time to time. Had to rollback to 3.2.4 as the issue doesn't seem to happen as often in that version.

**Comment by lon-yang** [comment]
This site https://ngx-markdown-editor.stackblitz.io/ is using the `3.3.1` now, and I failed to reproduce the issue. Are there any other details?

**Comment by nbittich** [comment]
with a very long text + some uploaded images, the scrolling in the preview panel is broken. it means I cannot scroll anymore. it happens from time to time with huge text + images that needs to be scrolled.

**Comment by lon-yang** [comment]
ok, I will test it
