### ISSUE TITLE
Sanitizing HTML

### ISSUE THREAD

**Issue by reevesba** [lon-yang/ngx-markdown-editor#84]
Hello, 

I have configured my md editor similar to the demo app. When I set markedjsOpt.sanitize to false, the HTML is still sanitized. 

Thanks.

**Comment by lon-yang** [comment]
Can you create a demo project on stackblitz?
I have tested at https://ngx-markdown-editor.stackblitz.io/, and it's not sanitized with code 
```html
<img src="" onerror="alert(1)" />
```

**Comment by reevesba** [comment]
Hey lon-yang, thanks for the response. I was eventually able to work around this.
