### ISSUE TITLE
Typo in tooltip

### ISSUE THREAD

**Issue by emahon** [lon-yang/ngx-markdown-editor#87]
For the blockquote (>) tool in the editor, the tooltip has a typo - it's spelled "Reference", not "Refrence"

The file to change is /src/lib/md-editor.html, the title text here:

```
<button class="btn btn-sm btn-default" type="button" title="Refrence" (click)="insertContent('Refrence')" *ngIf="!hideIcons.Refrence">
    <i class="fa fa-quote-left"></i>
</button>
```

**Comment by lon-yang** [comment]
Changed. Thanks.
