### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by cactuschibre** [lon-yang/ngx-markdown-editor#93]
Hello,

I have identified an XSS vulnerability on the last version of ngx-markdown-editor (3.3.2 - Last commit 783fe2df2f7709b2ac8bba5e1bea42074d48ce0d).

Payload :
![image](https://user-images.githubusercontent.com/2116674/114534270-1bf01380-9c4f-11eb-819a-65c661e2cfb6.png)

Previewed as:
![image](https://user-images.githubusercontent.com/2116674/114533678-6fae2d00-9c4e-11eb-9c63-ae093eed4f5e.png)

The XSS:
![image](https://user-images.githubusercontent.com/2116674/114533871-aa17ca00-9c4e-11eb-9611-7d29cd256d4d.png)

**Comment by lon-yang** [comment]
You can set this `markedjsOpt.sanitize` to `true`. That's can prevent this.

**Comment by cactuschibre** [comment]
The option is already set to true. 
It blocks other payloads, but not this one. 
I used the preconfigured "demo" subfolder from this repository.

**Comment by lon-yang** [comment]
Please using `3.3.3`. This version has been fixed this issue.
